DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS post;

CREATE TABLE "user" (
  id SERIAL PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id SERIAL PRIMARY KEY,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES "user" (id)
);
GRANT ALL PRIVILEGES ON DATABASE flaskr TO flaskr_admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO flaskr_admin;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public to flaskr_admin;