name: CI (testing)


on:
  push:
    branches:
      - '*'
      
jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello, World!"

  tests:
    runs-on: ubuntu-latest

    steps:
      # Clone repo into runner's memory.
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up python env in the runner's memory.
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      # Install requirements.
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./ 

      - name: Print Current Working Directory
        run: |
          pwd  # Print the current working directory
        working-directory: ${{ github.workspace }}  # Set the working directory to the root of your repository

      - name: List Directory Contents
        run: |
          ls  # List the directory contents
        working-directory: ${{ github.workspace }}  # Set the working directory to the root of your repository


      