name: CI/CD

on:
  push:
    branches:
      - '*'
      
jobs:

  tests:
    runs-on: ubuntu-latest

    steps:
      # Clone repo into runner's memory.
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up python env in the runner's memory.
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      # Install requirements.
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./ 

      # Add project directory to PYTHONPATH.
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      # Setup static file path for testing.
      - name: Set Environment Variables
        run: echo "STATIC_FILE_PATH=./static" >> $GITHUB_ENV

      # Modify permissions.
      - name: Modify permissions
        run: chmod -R 755 ./

      # Run unit tests.
      - name: Run unit tests
        run: pytest
        working-directory: ./
      
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Clone repo into runner's memory.
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up python env in the runner's memory.
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: blog-flaskr  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}  # Set this in your repository's secrets
          package: .  # The path to your application code
