name: CI/CD

on:
  push:
    branches:
      - '*'
      
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Clone repo into runner's memory.
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up python env in the runner's memory.
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.11

      # Install requirements.
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./ 

      # Add project directory to PYTHONPATH.
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      # Setup static file path for testing.
      - name: Set Environment Variables
        run: echo "STATIC_FILE_PATH=./static" >> $GITHUB_ENV

      # Modify permissions.
      - name: Modify permissions
        run: chmod -R 755 ./

      # Run unit tests.
      - name: Run unit tests
        run: pytest
        working-directory: ./

  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/213209037269/locations/global/workloadIdentityPools/flaskr/subject/SUBJECT_ATTRIBUTE_VALUE'
        service_account: 'singular-citron-331610@appspot.gserviceaccount.com'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v1'

    # Example of using the output
    - id: 'test'
      run: 'curl "${{ steps.deploy.outputs.url }}"'

  # build-and-deploy:
  #   needs: tests 
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Log in to Azure Container Registry
  #       run: |
  #         echo ${{ secrets.AZURE_PASSWORD }} | docker login regflaskr.azurecr.io --username ${{ secrets.AZURE_USERNAME }} --password-stdin

  #     - name: Build and push Docker image
  #       run: |
  #         docker build -t regflaskr.azurecr.io/flaskr_blog:${{ github.sha }} .
  #         docker push regflaskr.azurecr.io/flaskr_blog:${{ github.sha }}

  #     - name: Deploy to Azure Web App
  #       uses: azure/webapps-deploy@v2
  #       with:
  #         app-name: blog-flaskr 
  #         images: 'regflaskr.azurecr.io/flaskr_blog:${{ github.sha }}'